#ifndef CUADRUPLOS_H
#define CUADRUPLOS_H

#include <stddef.h>

// Enumeración de operaciones soportadas por los cuádruplos
typedef enum
{
    CUAD_OPERACION_ASIGNACION,
    CUAD_OPERACION_SUMA,
    CUAD_OPERACION_RESTA,
    CUAD_OPERACION_MULTIPLICACION,
    CUAD_OPERACION_DIVISION,
    CUAD_OPERACION_MODULO,
    CUAD_OPERACION_NEGATIVO,
    CUAD_OPERACION_AND,
    CUAD_OPERACION_OR,
    CUAD_OPERACION_NOT,
    CUAD_OPERACION_MENOR_QUE,
    CUAD_OPERACION_MAYOR_QUE,
    CUAD_OPERACION_MENOR_O_IGUAL,
    CUAD_OPERACION_MAYOR_O_IGUAL,
    CUAD_OPERACION_IGUAL,
    CUAD_OPERACION_DIFERENTE,
    CUAD_OPERACION_SALTAR,
    CUAD_OPERACION_SALTAR_SI_CIERTO,
    CUAD_OPERACION_SALTAR_SI_FALSO,
    CUAD_OPERACION_ETIQUETA,
    CUAD_OPERACION_PARAMETRO,
    CUAD_OPERACION_LLAMADA,
    CUAD_OPERACION_RETORNO,
    CUAD_OPERACION_RESERVAR_ARREGLO,
    CUAD_OPERACION_ASIGNAR_EN_ARREGLO,
    CUAD_OPERACION_ACCESO_ARREGLO,
    CUAD_OPERACION_IMPRIMIR_CADENA,
    CUAD_OPERACION_IMPRIMIR_ENTERO,
    CUAD_OPERACION_IMPRIMIR_FLOTANTE,
    CUAD_OPERACION_IMPRIMIR_DOBLE,
    CUAD_OPERACION_IMPRIMIR_CARACTER,
    CUAD_OPERACION_IMPRIMIR_BOOLEANO,
    CUAD_OPERACION_FIN_PROGRAMA
} OperacionCuadruplo;

// Representa un cuádruplo individual.
typedef struct
{
    OperacionCuadruplo operacion;
    char *argumento1;
    char *argumento2;
    char *resultado;
} Cuadruplo;

#endif // CUADRUPLOS_H
